namespace: "mateothegreat"
name: "k3s-osx"
version: "0.0.1"
readme: "README.md"
authors:
  - "Matthew Davis (https://matthewdavis.io)"
description: "Kubernetes on OSX via multipass."
license: ["MIT"]
tags: ["osx", "k3s", "multipass"]
repository: "https://github.com/mateothegreat/ansible-k3s-osx.git"
homepage: "https://github.com/mateothegreat/ansible-k3s-osx"
issues: "https://github.com/mateothegreat/ansible-k3s-osx/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc"
